name: Daily Niche Update

on:
  schedule:
    - cron: '0 6 * * *'  # Jeden Tag um 6:00 UTC (8:00 MEZ)
  workflow_dispatch:     # manuell auslösbar

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Repository klonen
        uses: actions/checkout@v3

      - name: 📦 Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 🔧 Abhängigkeiten installieren
        run: |
          pip install -r requirements.txt

      - name: 🚀 Skript ausführen
        run: |
          python py.mike.py

      - name: 🔼 Änderungen pushen
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update via GitHub Actions" || echo "No changes"
          git push
